export const environment = {
    sidenav: [
        { link: 'form', icon: 'description', title: 'Form' },
        { link: 'list', icon: 'dns', title: 'List' },
        // { link: 'table', icon: 'table', title: 'Table' },
        // { link: 'card', icon: 'payment', title: 'Card' },
        // { link: 'grid', icon: 'grid_view', title: 'Grid' },
        // { link: 'address', icon: 'home', title: 'Address' },
        // { link: 'posts', icon: 'rss_feed', title: 'Posts' },
        // { link: 'tree', icon: 'account_tree', title: 'Tree' },
        // { link: 'dashboard', icon: 'dashboard', title: 'Dashboard' },
        // { link: 'grid-demo', icon: 'grid_view', title: 'Grid List Demo' },
        // { link: 'drag-drop', icon: 'drag_indicator', title: 'Drag and Drop' },
        { link: '', icon: '', title: '' },
        { link: 'settings', icon: 'settings', title: 'Settings' },
        { link: 'faq', icon: 'help', title: 'FAQ' },
        { link: 'policy', icon: 'verified_user', title: 'Policy' },
        { link: '', icon: '', title: '' },
        { link: '', icon: 'power_settings_new', title: 'Logout' },
    ],
};
